language: java
jdk:
  - openjdk11
  - openjdk8
cache:
  directories:
    - $HOME/.m2
install: echo "Skipping pre-fetch of maven dependencies"
before_script: mvn validate formatter:validate -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
script: mvn clean verify javadoc:jar source:jar site -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
after_success: mvn -Ptravis jacoco:merge jacoco:report coveralls:report -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
